### ISSUE TITLE
custom manager and queryset methods not working

### ISSUE THREAD

**Issue by smcoll** [makinacorpus/django-safedelete#44]
i'll issue a PR shortly with failing tests which should give a clearer picture.  Let me know if i misunderstood the usage of the factory.

**Comment by Gagaro** [comment]
You need to set the custom queryset and the manager on the same model. I added your PR corrected on master:

https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/tests.py#L52-L66

Because the base manager inherit from the class you pass to the factory, your `get_queryset` method is actually overridden (https://github.com/makinacorpus/django-safedelete/blob/master/safedelete/managers.py#L41).

This is kind of counter intuitive, this is one of the reason why I wanted to remove the factory. You can take a look at the 0.4.x branch (https://github.com/makinacorpus/django-safedelete/tree/0.4.x) in which I removed them. I still want to do some things before release (#43), but it should be fairly stable.

**Comment by smcoll** [comment]
@Gagaro much appreciated.
