### ISSUE TITLE
prefetch_related are re-evaluated

### ISSUE THREAD

**Issue by Gagaro** [makinacorpus/django-safedelete#81]
see 921b3fb72e67cddfb0964b82dc1bd0b7ac0eb2d6

**Comment by sathoro** [comment]
This is because of the implementation of `all` on `SafeDeleteManager`. It calls the queryset's `all` method, however Django's default implementation does not. Calling `all` on a queryset creates a clone. Clones do not copy over cached prefetch_related lookups.

This is what the Django source code looks like (`django/db/models/manager.py`), with a comment about why it doesn't call `all`:

```
def all(self):
    # We can't proxy this method through the `QuerySet` like we do for the
    # rest of the `QuerySet` methods. This is because `QuerySet.all()`
    # works by creating a "copy" of the current queryset and in making said
    # copy, all the cached `prefetch_related` lookups are lost. See the
    # implementation of `RelatedManager.get_queryset()` for a better
    # understanding of how this comes into play.
    return self.get_queryset()
```

I removed the `all` call and it no longer re-evaluates prefetch_related lookups but I'm wondering if it was calling `all` for a reason or if it is safe to remove?

**Comment by sathoro** [comment]
Here is what I have changed the `SafeDeleteManager`.`all` method to in order to support `force_visibility` and still keep the cached lookups.

```
def all(self, *args, **kwargs):
    force_visibility = kwargs.pop('force_visibility', None)

    qs = super(SoftDeleteManager, self).all(*args, **kwargs)

    if force_visibility is not None:
        qs._safedelete_force_visibility = force_visibility

    return qs
```

**Comment by Gagaro** [comment]
Thanks a lot and sorry for the delay, it's fixed on master.
