### ISSUE TITLE
How to create custom mangers for models inheriting SafeDeleteModel?

### ISSUE THREAD

**Issue by ciarancourtney** [makinacorpus/django-safedelete#85]
Per the [docs](https://docs.djangoproject.com/en/1.11/topics/db/managers/#custom-managers-and-model-inheritance) it seems that it should be possible to add additional custom managers to a model, if the SafeDeleteModel is initializing objects property, but this doesn't seem to be the case. If I add a custom manager to a model, model._default_manager will be that manager.

Shouldn't SafeDeleteModel define a default_manager_name?

**Comment by Gagaro** [comment]
Because your manager will be the first on your model. You should add `objects = SafeDeleteManager()` before or set `default_manager_name` to objects in your model.

I'm not sure we should set it on the `SafeDeleteModel` directly as defining a new manager on your model wouldn't have the expected behavior.

**Comment by ciarancourtney** [comment]
Thanks @Gagaro I'm working around by setting `default_manager_name = 'objects'`.
